#include <stdio.h>
#include <string.h>
#include "../src/core/EulNodeList/EulNodeList.h"
#include "../src/core/EulSourceFile/EulSourceFile.h"
#include "../src/core/EulProgram/EulProgram.h"
#include "../src/core/Compiler/Compiler.h"
#include "../src/core/EulToken/EulToken.h"



#define YYSTYPE EulToken*
#define YY_DECL int yylex(YYSTYPE * yylval_param, void* yyscanner, Compiler *compiler)
#include "../src/parser/autoGenerated.EulSyntax.h"
#include "../src/lexer/autoGenerated.EulLexer.h"


#include "TestUtils.h"
#include "core/NodeListTest.h"
#include "core/SourceFileTest.h"
#include "core/EulProgramTest.h"
#include "core/CompilerTest.h"

#include "lexer/VocabularyTest.h"
#include "parser/SyntaxTest.h"




int main() {
	//1. core tests
	NodeListTest_runAllTests();
	SourceFileTest_runAllTests();
	EulProgramTest_runAllTests();
	CompilerTest_runAllTests();

	//2. Lexer related tests
	VocabularyTest_runAllTests();

	//3. Parser related tessts
	SyntaxTest_runAllTests();


	printf("All tests passed successfully.\n");
	return 0;
}
