#include <stdio.h>
#include <string.h>
#include "../src/core/EulToken.h"
#include "../src/Compiler.h"

#include "../src/core/EulToken.Functions.h"



#define YYSTYPE EulToken*
#define YY_DECL int yylex(YYSTYPE * yylval_param, void* yyscanner, Compiler *compiler)
#include "../src/parser/autoGenerated.EulSyntax.h"
#include "../src/lexer/autoGenerated.EulLexer.h"


#include "TestUtils.h"
#include "lexer/VocabularyTest.h"
#include "parser/SyntaxTest.h"
#include "core/NodeTest.h"
#include "core/NodeListTest.h"
#include "core/SourceFileTest.h"


int main() {
	//core tests
	NodeTest_runAllTests();
	NodeListTest_runAllTests();
	SourceFileTest_runAllTests();

	//Lexer related tests
	VocabularyTest_runAllTests();
	SyntaxTest_runAllTests();


	printf("All tests passed successfully.\n");
	return 0;
}
