#include <stdlib.h>
#include <string.h>
#include "../../constants/Constants.h"
#include "../EulNodeList/EulNodeList.h"
#include "../EulSourceFile/EulSourceFile.h"
#include "../EulProgram/EulProgram.h"
#include "../Compiler/Compiler.h"
#include "EulToken.h"


#define YYSTYPE EulToken*
#define YY_DECL int yylex(YYSTYPE * yylval_param, void* yyscanner, Compiler *compiler)
#include "../../parser/autoGenerated.EulSyntax.h"






//region GLOBAL TOKEN FUNCTIONS
/** A do-nothing deinit. */
void EulToken_deinitEmpty(EulToken* this) {}
//endregion




//region INT VALUE
/** CLASS object */
EulTokenClass IntTokenClass = {
    EulToken_deinitInt
};

void EulToken_initInt(EulToken* this, char* text) {
    this->class = &IntTokenClass;

    IntTokenValue* value = malloc(sizeof(IntTokenValue));
    value->value = strtoul(text, &text, 10);		//setup value
    if (*text) { //setup signed or unsigned flag
        value->isUnsigned = (*text) == 'u';
        text++;
    }
    else value->isUnsigned = 0; //default is signed

    if (*text) value->size = strtoul(text, &text, 10);	//setup size, if any
    else value->size = EUL_LANG_DEFAULT_INT_SIZE;

    this->value.asInt = value;
}

void EulToken_deinitInt(EulToken* this) {
    free(this->value.asInt);
}
//endregion




//region FLOAT VALUE
/** CLASS object */
EulTokenClass FloatTokenClass = {
    EulToken_deinitFloat
};

void EulToken_initFloat(EulToken* this, char* text) {
    this->class = &FloatTokenClass;
    FloatTokenValue* tokenVal = malloc( sizeof(FloatTokenValue) );

    tokenVal->value = strtod(text, &text);
    if (*text == 'f') text++; //skip f character, if any

    if (*text) tokenVal->size = strtoul(text, &text, 10);
    else tokenVal->size = EUL_LANG_DEFAULT_FLOAT_SIZE;

    this->value.asFloat = tokenVal;
}

void EulToken_deinitFloat(EulToken* this) {
    free(this->value.asFloat);
}
//endregion




//region ID VALUE
EulTokenClass IdTokenClass = {
    EulToken_deinitId
};

void EulToken_initId(EulToken* this, char* text, unsigned int len) {
    this->class = &IdTokenClass;

    //1. Setup string for id name
    this->value.asId = malloc(len+1);
    strcpy(this->value.asId, text);
}

void EulToken_deinitId(EulToken* this) {
    free(this->value.asId);
}
//endregion




//region CHAR VALUE
EulTokenClass CharTokenClass = {
    EulToken_deinitChar
};

void EulToken_initSimpleChar(EulToken* this, char* text, unsigned int len, Compiler *compiler) {
    this->class = &CharTokenClass;

    IntTokenValue* value = malloc(sizeof(IntTokenValue));
    value->size = len - 2; //we default the char size to its UTF length. We substract 2, because there are the '' quotes.

    switch(len) {
        case 3: //1 byte unicode
            value->value = (unsigned char) ( *(text+1) );
            break;

        case 4: //2 byte unicode
            value->value = ((unsigned char)text[1])<<8 | (unsigned char)text[2];
            break;

        case 6: //4 byte unicode
            value->value = ((unsigned char)text[1])<<24 | ((unsigned char)text[2])<<16 |
                                      ((unsigned char)text[3])<<8 | (unsigned char)text[4];
            break;

        default:
            Compiler_makeLexerError(compiler, "Invalid char size");
            return;
    }

    this->value.asInt = value;
}


void EulToken_initEscapedChar(EulToken* this, unsigned int value) {
    this->class = &CharTokenClass;
    IntTokenValue* tokenVal = malloc(sizeof(IntTokenValue));

    tokenVal->value = value;
    tokenVal->size = 1;		//all escaped characters are 1 byte long

    this->value.asInt = tokenVal;
}

void EulToken_deinitChar(EulToken* this) {
    free(this->value.asInt);
}
//endregion




//region STRING VALUE
EulTokenClass StringTokenClass = {
    EulToken_deinitString
};

void EulToken_initStringFromBuffer(EulToken* this, Compiler *compiler) {
    this->class = &StringTokenClass;

    Compiler_addToStringBuffer(compiler, '\0'); //terminate the string
    this->value.asString = malloc(compiler->stringBufferIndex); //make space for the string in token
    strcpy(this->value.asString, compiler->stringBuffer);	//copy the string
}

void EulToken_deinitString(EulToken* this) {
    free(this->value.asString);
}
//endregion




//region LIST VALUE
EulTokenClass ListTokenClass = {
    EulToken_deinitList
};

void EulToken_initList(EulToken* this) {
    this->class = &ListTokenClass;
    this->value.asList = malloc(sizeof(EulNodeList));
    EulNodeList_init(this->value.asList);
}

void EulToken_initListWith(EulToken* this, EulToken* element) {
    this->class = &ListTokenClass;
    this->value.asList = malloc(sizeof(EulNodeList));
    EulNodeList_init(this->value.asList);
    EulNodeList_push(this->value.asList, element);
}

void EulToken_deinitList(EulToken* this) {
    EulNodeList_deinit(this->value.asList);
    free(this->value.asList);
}
//endregion