#include <stdlib.h>
#include "../EulNodeList/EulNodeList.h"
#include "EulSourceFile.h"
#include "../EulToken/EulToken.h"
#include "../../parser/autoGenerated.EulSyntax.h"



/** CLASS object */
EulTokenClass FileTokenClass = {
    EulSourceFile_deinit
};



//region LIFE CYCLE
void EulSourceFile_init(EulToken* this, char* id) {
    //1. setup type
    this->class = &FileTokenClass;

    //2. init value
    EulSourceFile* value = malloc( sizeof(EulSourceFile) );
    this->value.asSourceFile = value;

    //4. setup value
    value->isParsed = 0;
    value->id = id;
    EulNodeList_init(&value->imports);
    EulNodeList_init(&value->exports);
    EulNodeList_init(&value->symbols);
    EulNodeList_init(&value->statements);
}

void EulSourceFile_deinit(EulToken* this) {
    EulSourceFile* value = this->value.asSourceFile;

    EulNodeList_deinit(&value->imports);
    EulNodeList_deinit(&value->exports);
    EulNodeList_deinit(&value->symbols);
    EulNodeList_deinit(&value->statements);

    free(value);
}
//endregion
