cd ../src

mkdir __autoGenerated__


flex -o __autoGenerated__/EulLexer.cpp lexer/lex.l
bison -d -v --file-prefix=__autoGenerated__/EulParser parser/parser.yy

clang++ \
    -std=c++11 \
    -o ../out/dummy \
    __autoGenerated__/EulParser.tab.cc \
    __autoGenerated__/EulLexer.cpp \
    core/EulToken/All.cpp \
    core/EulSourceFile/EulSourceFile.cpp \
    core/EulProgram/EulProgram.cpp \
    core/Compiler/Compiler.cpp \
    DummyMain.cpp


#clean up
rm -rf ./__autoGenerated__