clear
clear
clear
cd ../src

bison --debug ../data/syntax.y
flex ../data/lex.l



clang++ -g -O3 \
    ../src/core/Compiler/Compiler.c \
    ../src/core/EulToken/EulToken.c \
    ../src/core/EulNodeList/EulNodeList.c \
    ../src/core/EulSourceFile/EulSourceFile.c \
    ../src/core/EulProgram/EulProgram.c \
    ../src/lexer/autoGenerated.EulLexer.c \
    ../src/parser/autoGenerated.EulSyntax.c \
    llvm/Main.cpp \
    -Wno-unknown-warning-option `llvm-config --cxxflags --ldflags --system-libs --libs core` \
    -o ../out/eulc


#cleanup
rm \
  ../src/parser/autoGenerated.EulSyntax.c \
  ../src/parser/autoGenerated.EulSyntax.h \
  ../src/lexer/autoGenerated.EulLexer.c  \
  ../src/lexer/autoGenerated.EulLexer.h


