#pragma once

enum class EulStatementType {
    UNKNOWN_STATEMENT,
    VAR_DECLARATION,
    IMPORT,
    EXPORT,
    EXPRESSION_STATEMENT,
    RETURN_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FUNC_DECLARATION_STATEMENT
};
