#include <stdlib.h>
#include <string.h>
#include "../../constants/Constants.h"
#include "../EulNodeList/EulNodeList.h"
#include "../EulSourceFile/EulSourceFile.h"
#include "../EulToken/EulToken.h"
#include "EulProgram.h"
#include "../../parser/autoGenerated.EulSyntax.h"




//region PROGRAM VALUE
void EulProgram_init(EulProgram* this) {
  //push it in sources list
  EulNodeList_init(&this->sources);
}


void EulProgram_deinit(EulProgram* this) {
  EulNodeList_deinit(&this->sources);
}


EulToken* EulProgram_getSource(EulProgram* this, char* id, char createIfNotExists) {
    if (id==0) return 0;

    //try finding the file
    EulNode *current = this->sources.first;
    while(current) {
        if (strcmp(id, current->value->value.asSourceFile->id)==0) return current->value;
        current = current->next;
    }

    //we did not find the token. What we should now do, depends on createIfNotExists.
    if (!createIfNotExists) return 0;

    //we create a token, add it on our list, and return it.
    EulToken* createdSource = malloc( sizeof(EulToken) );
    EulSourceFile_init(createdSource, id);
    EulNodeList_push(&this->sources, createdSource);

    return createdSource;
}


/**
  Will be probably called by the Compiler object every time it needs to get the next source file.
  returns a token with type EulTokenType_SOURCE_FILE,
          null if all files are parsed.
*/
EulToken* EulProgram_nextPendingSource(EulProgram* this) {
  EulNode *current = this->sources.first;
  while(current) {
    if (current->value->value.asSourceFile->isParsed==0) return current->value;
    current = current->next;
  }

  //all files are parsed. return null.
  return 0;
}
//endregion